@artist = Artist.create!(name: "Daft Punk")
@artist1 = Artist.create!(name: "Blops")
@artist2 = Artist.create!(name: "Basf")

@song = @artist.songs.create!(title: "The Grid")
@song1 = @artist.songs.create!(title: "The asgkhaskj")
@song2 = @artist1.songs.create!(title: "The akhskg")
@song3 = @artist2.songs.create!(title: "The akhsfjahs")
@song4 = @artist1.songs.create!(title: "The akshg")
@song5 = @artist2.songs.create!(title: "The kajshf")
